version: '3'

services:
  ppgadmin:
    container_name: arbeitsbuch-pgadmin
    image: dpage/pgadmin4:4.29
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.ch
      - PGADMIN_DEFAULT_PASSWORD=secret
    ports:
      - "5050:80"
    networks:
      - arbeitsbuch
    volumes:
      - pgadmin-data:/root/.pgadmin
    depends_on:
      - postgres

  postgres:
    container_name: arbeitsbuch-postgres
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=arbeitsbuch
    ports:
      - "5432:5432"
    networks:
      - arbeitsbuch
    volumes:
      - postgres-db:/var/lib/postgresql/data

networks:
  arbeitsbuch:
    driver: bridge

volumes:
  postgres-db:
  pgadmin-data:

